// <auto-generated />
namespace RestoBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RestoBookDBContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RestoBookDBContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201503260855279_RestoBookDBContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
